### ISSUE TITLE
several views are giving  psycopg2.ProgrammingError

### ISSUE THREAD

**Issue by Michon-BS** [flask-dashboard/Flask-MonitoringDashboard#180] opened 2018-07-02 02:09 UTC
I am getting the following error; any ideas?

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: double precision <= timestamp without time zone

LINE 3: ...mestamp AND "monitoringRequest".duration <= '2018-0...

HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: 'SELECT "monitoringRequest".time_requested AS "monitoringRequest_time_requested" \nFROM "monitoringRequest" \nWHERE "monitoringRequest".time_requested >= %(time_requested_1)s AND "monitoringRequest".duration <= %(duration_1)s'] [parameters: {'time_requested_1': datetime.datetime(2018, 6, 11, 14, 0), 'duration_1': datetime.datetime(2018, 7, 2, 13, 59, 59)}]

**Comment by bogdanp05** [comment] 2018-07-02 20:22
Hi @Michon-BS,

Could you provide some extra info? What database system are you using? Which version of the Flask Monitoring Dashboard? Do you get the error at startup or when accessing a particular screen?

Regards,
Bogdan

**Comment by Michon-BS** [comment] 2018-07-03 00:09
Hi @bogdanp05 ,

Thanks for your reply. I'm using Postgresql; connection string in config.cfg is DATABASE=postgresql://user:pwd@host:5432/database.

Dashboard is running fine, but there are several views giving this error. Hope this helps.
![image](https://user-images.githubusercontent.com/7202084/42191868-9d5ce85c-7ea8-11e8-9bd4-6a4cb5b4236c.png)

**Comment by Harold2017** [comment] 2018-07-03 03:12
Hi @bogdanp05 ,

It may be caused by that the duration is float type and it cannot be compared with datetime type.

**Comment by bogdanp05** [comment] 2018-07-04 14:46
Hi @Michon-BS ,

I managed to replicate the error. It's cause by PostgreSQL, in the sense that some queries are not compatible with it. We are working on it on branch `issue180`.
In the meantime, you can try using the Dashboard with  SQLite or MySQL.

Regards,
Bogdan

**Comment by bogdanp05** [comment] 2018-07-13 10:13
Hi @Michon-BS,

The issue is now fixed with pull request #183 . I used PostgreSQL 10.4 to test it, but it should work with previous versions as well.

Regards,
Bogdan

**Comment by Michon-BS** [comment] 2018-07-13 10:35
Hi @bogdanp05 ,

Many thanks! Can confirm it's now working...

Cheers,
Dennis

**Closed** 2018-07-13 10:41 UTC

**Comment by bogdanp05** [comment] 2019-04-02 16:00
Hi @Michon-BS,

If you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see

Regards,
Bogdan
