### ISSUE TITLE
MySql database connection error

### ISSUE THREAD

**Issue by marinswk** [flask-dashboard/Flask-MonitoringDashboard#102] opened 2018-05-02 12:34 UTC
herllo i'm trying to specify a path to a mysql db in the config file:
DATABASE=mysql://username:pswd@host/db_name

and i get the sequent stack trace error when trying to run the app.py for my flask project:

```
Traceback (most recent call last):
  File "/home/andreamarino/www/flask_project/app.py", line 21, in <module>
    dashboard.bind(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/__init__.py", line 64, in bind
    import flask_monitoringdashboard.views
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/views/__init__.py", line 11, in <module>
    from . import dashboard
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/views/dashboard/__init__.py", line 12, in <module>
    from flask_monitoringdashboard.views.dashboard.endpoints import page_boxplot_per_endpoint
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/views/dashboard/endpoints.py", line 6, in <module>
    from flask_monitoringdashboard.core.utils import simplify
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/core/utils.py", line 7, in <module>
    from flask_monitoringdashboard.database.endpoint import get_monitor_rule
  File "/usr/local/lib/python2.7/dist-packages/flask_monitoringdashboard/database/__init__.py", line 121, in <module>
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1074, "Column length too big for column 'stacktrace' (max = 21845); use BLOB or TEXT instead") [SQL: u'\nCREATE TABLE outliers (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tendpoint VARCHAR(250) NOT NULL, \n\trequest_values VARCHAR(10000), \n\trequest_headers VARCHAR(10000), \n\trequest_environment VARCHAR(10000), \n\trequest_url VARCHAR(1000), \n\tcpu_percent VARCHAR(100), \n\tmemory VARCHAR(10000), \n\tstacktrace VARCHAR(100000), \n\texecution_time FLOAT NOT NULL, \n\ttime DATETIME, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by bogdanp05** [comment] 2018-05-03 00:05
Hi Andrea,

I managed to replicate the error. It was caused by the fact that MySQL uses a size limit for columns, limit that we passed in the case of the `stacktrace` column. I pushed a fix for this issue on the development branch.

**Comment by marinswk** [comment] 2018-05-03 08:02
that's great and super responsive ;) should i get the development branch or will you merge in master soon?

**Comment by bogdanp05** [comment] 2018-05-03 08:44
Hi! We will probably merge into master tomorrow, but of course, you can also get the development branch if you'd like. I will close this issue now.

**Closed** 2018-05-03 08:44 UTC
