### ISSUE TITLE
hourly_load broken with Postgres

### ISSUE THREAD

**Issue by dannyeuu** [flask-dashboard/Flask-MonitoringDashboard#186] opened 2018-08-03 22:16 UTC
There is a problem with this endpoint `/dashboard/hourly_load` comparing `datetime` with `float`

```
  File "/home/schrubles/.virtualenvs/schrubles/lib/python3.5/site-packages/flask_monitoringdashboard/views/dashboard/heatmap.py", line 30, in hourly_load
    return render_template('fmd_dashboard/graph.html', form=form, graph=hourly_load_graph(form), title=TITLE,
  File "/home/schrubles/.virtualenvs/schrubles/lib/python3.5/site-packages/flask_monitoringdashboard/views/dashboard/heatmap.py", line 53, in hourly_load_graph
    for time, count in get_num_requests(db_session, endpoint_id, start_datetime, end_datetime):
  File "/home/schrubles/.virtualenvs/schrubles/lib/python3.5/site-packages/flask_monitoringdashboard/database/endpoint.py", line 26, in get_num_requests
    result = query.filter(Request.time_requested >= start_date, Request.duration <= end_date).all()

HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: 'SELECT "monitoringRequest".time_requested AS "monitoringRequest_time_requested" \nFROM "monitoringRequest" \nWHERE "monitoringRequest".time_requested >= %(time_requested_1)s AND "monitoringRequest".duration <= %(duration_1)s'] [parameters: {'time_requested_1': datetime.datetime(2018, 7, 14, 0, 0), 'duration_1': datetime.datetime(2018, 8, 3, 23, 59, 59)}] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by bogdanp05** [comment] 2018-08-04 19:42
Thanks for signaling this error! This will be fixed sometime next week.

Regards,
Bogdan

**Comment by dannyeuu** [comment] 2018-08-06 19:26
thanks @bogdanp05

**Comment by bogdanp05** [comment] 2018-09-04 17:34
Hi @dannyeuu,

The problem is now fixed on the master branch. Sorry it took so long to solve.

Regards,
Bogdan

**Closed by bogdanp05** 2018-09-04 17:34 UTC

**Comment by bogdanp05** [comment] 2019-04-02 15:59
Hi @dannyeuu,

If you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see

Regards,
Bogdan
